# Generated by Django 5.1 on 2025-10-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Буква')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('skill1', models.IntegerField(default=0, verbose_name='Креативность')),
                ('skill2', models.IntegerField(default=0, verbose_name='Визуальное мышление')),
                ('skill3', models.IntegerField(default=0, verbose_name='Логика')),
                ('skill4', models.IntegerField(default=0, verbose_name='Аналитика')),
                ('skill5', models.IntegerField(default=0, verbose_name='Организация')),
                ('skill6', models.IntegerField(default=0, verbose_name='Структурирование')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tanda.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
