# Generated by Django 5.1 on 2025-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('skill1', 'Креативность'), ('skill2', 'Визуальное мышление'), ('skill3', 'Логика'), ('skill4', 'Аналитика'), ('skill5', 'Организация'), ('skill6', 'Структурирование')], verbose_name='Навык')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('image', models.ImageField(upload_to='tanda/photos/%Y/%m', verbose_name='Изображение')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
    ]
