# Generated by Django 5.2.9 on 2026-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanda', '0004_reset_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='profession',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tanda/photos/%Y/%m', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='skill',
            field=models.CharField(choices=[('skill1', 'Креативность'), ('skill2', 'Визуальное мышление'), ('skill3', 'Логика'), ('skill4', 'Аналитика'), ('skill5', 'Организация'), ('skill6', 'Структурирование')], max_length=10, verbose_name='Навык'),
        ),
    ]
